# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_detector', '0006_auto_20170708_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='super_detector.SubCategory'),
            preserve_default=False,
        ),
    ]
