# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_detector', '0007_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='super_detector.SubCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='super_detector.Brand'),
        ),
    ]
